// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwYe_p5k4_Fgr_gcjXxKi5C_3i4Y2gKM',
    appId: '1:465969396494:web:d5bc75bc789ba65595355f',
    messagingSenderId: '465969396494',
    projectId: 'giftapp-75fc9',
    authDomain: 'giftapp-75fc9.firebaseapp.com',
    storageBucket: 'giftapp-75fc9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3rpreUOJLlyT2NLFD3YUKLjFoHiHG4d8',
    appId: '1:465969396494:android:fefc4df923da683695355f',
    messagingSenderId: '465969396494',
    projectId: 'giftapp-75fc9',
    storageBucket: 'giftapp-75fc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwgorPnimos_iNrMMSxlXUaI5CCxKqf7o',
    appId: '1:465969396494:ios:98f9511bc72dd96495355f',
    messagingSenderId: '465969396494',
    projectId: 'giftapp-75fc9',
    storageBucket: 'giftapp-75fc9.firebasestorage.app',
    iosBundleId: 'com.example.giftapp',
  );
}
